version: "3.9"
services:
  mongo-db:
    image: mongo:8.0.10
    container_name: mongo-db
    hostname: d521c7041405
    mac_address: fa:04:77:94:49:76
    ports:
      - "27023:27017"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GOSU_VERSION: "1.17"
      JSYAML_VERSION: "3.13.1"
      JSYAML_CHECKSUM: 662e32319bdd378e91f67578e56a34954b0a2e33aca11d70ab9f4826af24b941
      MONGO_PACKAGE: mongodb-org
      MONGO_REPO: repo.mongodb.org
      MONGO_MAJOR: "8.0"
      MONGO_VERSION: 8.0.10
      HOME: /data/db
      GLIBC_TUNABLES: glibc.pthread.rseq=0
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    networks:
      default:
        aliases:
          - mongo-db
    restart: "no"
    labels:
      org.opencontainers.image.ref.name: ubuntu
      org.opencontainers.image.version: "24.04"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]  # Esto es solo si quieres extenderlo a otros entornos con GPU
    runtime: runc

volumes:
  mongo_configdb:
  mongo_db: